In [1]:
#Defining a non singular matrix as Key from which the Public Key and Private Key are derived
import numpy as np
import scipy.linalg
#Dictionary for AlphaNumeric values
AlphaNums = { "a":1, "b":2, "c":3,"d":4, "e":5, "f":6, "g":7, "h":8, "i":9, "j":10, "k":11, "l":12, "m":13, "n":14,
             "o":15,"p":16, "q":17, "r":18, "s":19, "t":20, "u":21, "v":22, "w":23, "x":24, "y":25, "z":26, " ":0}

K=np.array([[3,9,27],[1,1,1],[2,4,8]])
print("Key Matrix:\n",K)

#Find Eigen Values
w, v = scipy.linalg.eig(np.array([[4, 1], [2, 3]]))
print("Eigen Values: ",w)
#print(v)

#Using scipy library for LU Decomposition we have
#L = Public Key for Encryption 
m = K.shape
P, L, U = scipy.linalg.lu(K)

#Rewriting K as product of L & U for further computations
K=np.dot(L,U)

#Message to be Encrypted
Msg="WelcomeTo"
Len = len(Msg)
print("The Message to be Encrypted: ", Msg)

#Converting message to a list
H = list(Msg)
X = list()
N = list()
for ch in H:
    X.append(AlphaNums[ch.lower()])
print("Numerical Equivalent: ",X)

#Converting the numerical equivalent message into array blocks of size(2 x 1)
H = np.array(X)

N=np.array_split(H,(Len/m[0]))
H=[N[0],N[1],N[2]]


#Choosing a random matrix A which will act as Hash for XoR operation
A=np.array([[3,2,7],[2,3,1],[3,4,1]])

#Using Xor operation to find the Cipher matrix
Ic = A ^ H

#Computing the Constant Matrix Cons
Cons=np.dot(K,Ic)

#Encrypting the message using lower triangular matrix as encryption key
print("Public Key:\n",L)
Linv = np.linalg.inv(L)
Y=np.around(np.dot(Linv,Cons))

Encrypted=[]
for c in Y:
    for d in c:
        for K,V in AlphaNums.items():
            if V == round(d%26):
                Encrypted.extend(K)

Enystr="";
for a in Encrypted:
    Enystr += a
print("The Encrypted Message:")
print(Enystr)

Key Matrix:
 [[ 3  9 27]
 [ 1  1  1]
 [ 2  4  8]]
Eigen Values:  [5.+0.j 2.+0.j]
The Message to be Encrypted:  WelcomeTo
Numerical Equivalent:  [23, 5, 12, 3, 15, 13, 5, 20, 15]
Public Key:
 [[1.         0.         0.        ]
 [0.33333333 1.         0.        ]
 [0.66666667 1.         1.        ]]
The Encrypted Message:
woybdtntx


In [2]:
#Decrypting the encoded Message using Private Key U
print("Private Key:\n",U)
Uinv = np.linalg.inv(U)
Ic1=np.dot(Uinv,Y)

Df=np.empty((3, 3))
for i in range(0,3):
    for j in range(0,3):
        Df[i][j] = int(np.round(Ic1[i][j]))^A[i][j]

D2=[]
for i in range(0,3):
    for j in range(0,3):
        for K,V in AlphaNums.items():
            if V == int(Df[i][j]):
                D2.extend(K)

Dcystr=""
for a in D2:
    Dcystr += a
print("The Decrypted Message:")
print(Dcystr)

Private Key:
 [[ 3.  9. 27.]
 [ 0. -2. -8.]
 [ 0.  0. -2.]]
The Decrypted Message:
welcometo
