Symmetric Key Cryptography using LU Factorization
1) Define a Non singular Matrix A nof size (2 x 2), this will act as our Key.

2) Using Inbuilt Python function we compute L & U matrix for A 

In [24]:
import pprint
import numpy
import scipy
import scipy.linalg   # SciPy Linear Algebra Library


A =numpy.array([ [4, 1], [2, 3]])
m= A.shape
P, L, U = scipy.linalg.lu(A)

print("A:")
pprint.pprint(A)

print("P:")
pprint.pprint(P)

print("L:")
pprint.pprint(L)

print("U:")
pprint.pprint(U)

print(m[0])


A:
array([[4, 1],
       [2, 3]])
P:
array([[1., 0.],
       [0., 1.]])
L:
array([[1. , 0. ],
       [0.5, 1. ]])
U:
array([[4. , 1. ],
       [0. , 2.5]])
2


Define the Numerical Alphabet relative dictionary.
Convert the Message into its numerical equivalent. 

In [26]:
import numpy as np
AlphaNums = { "a":1, "b":2, "c":3,"d":4, "e":5, "f":6, "g":7, "h":8, "i":9, "j":10, "k":11, "l":12, "m":13, "n":14, "o":15,"p":16, "q":17, "r":18, "s":19, "t":20, "u":21, "v":22, "w":23, "x":24, "y":25, "z":26, " ":0}
Msg="Welcome "
Len = len(Msg)
#Converting message to a list
H = list(Msg)
X = list()
N = list()
print(H)
print(Len)
for ch in H:
    print(AlphaNums[ch.lower()])
    X.append(AlphaNums[ch.lower()])
print(X)
#Converting the numerical equivalent message into array blocks of size(2 x 1)
P = np.array(X)
print(P)
N=np.array_split(P,(Len/m[0]))
print(N[0]) 

['W', 'e', 'l', 'c', 'o', 'm', 'e', ' ']
8
23
5
12
3
15
13
5
0
[23, 5, 12, 3, 15, 13, 5, 0]
[23  5 12  3 15 13  5  0]
[23  5]


In [27]:
#Encrypt the message
#Apply Hill Enccryption formula
K = np.dot(L,U)
print(K)
Ey=[]
J={}
C={}
k=int(Len/2);
for i in range(0,k):
    J[i] = (np.dot(K,N[i]))
    C[i]=J[i]%26
    C[i].tolist()
    Ey.extend(C[i])
print(Ey)

Encrypted=[]
for c in Ey:
    for K,V in AlphaNums.items():
        if V == c:
            Encrypted.extend(K)
print(Encrypted)

Enystr="";
for a in Encrypted:
    Enystr += a
print("The Encrypted Message:")
print(Enystr)

[[4. 1.]
 [2. 3.]]
[19.0, 9.0, 25.0, 7.0, 21.0, 17.0, 20.0, 10.0]
['s', 'i', 'y', 'g', 'u', 'q', 't', 'j']
The Encrypted Message:
siyguqtj


In [28]:
#Decryption of a Message
#Find the inverse of LU
D = np.dot(L,U)
I = np.linalg.inv(D)
print(I)

[[ 0.3 -0.1]
 [-0.2  0.4]]


In [29]:
D1=[]
L={}
for j in range(0,k):
    L[j] = np.dot(I,J[j])%26
    print(L[j])
    D1.extend(L[j].tolist())
print(D1)

[23.  5.]
[12.  3.]
[15. 13.]
[5. 0.]
[22.999999999999996, 5.0, 11.999999999999998, 3.0, 14.999999999999998, 13.0, 5.0, 0.0]


In [30]:
D2=[]
for x in D1:
    for K,V in AlphaNums.items():
        if V == round(x):
            D2.extend(K)
print(D2)

Dcystr=""
for a in D2:
    Dcystr += a
print("The Decrypted Message:")
print(Dcystr)

['w', 'e', 'l', 'c', 'o', 'm', 'e', ' ']
The Decrypted Message:
welcome 
