Symmetric Key Cryptography using LU Factorization
1) Define a Non singular Matrix A nof size (2 x 2), this will act as our Key.

2) Using Inbuilt Python function we compute L & U matrix for A 

In [1]:
import pprint
import numpy
import scipy
import scipy.linalg   # SciPy Linear Algebra Library


A =numpy.array([ [4, 1], [2, 3]])
m= A.shape
P, L, U = scipy.linalg.lu(A)

print("A:")
pprint.pprint(A)

print("P:")
pprint.pprint(P)

print("L:")
pprint.pprint(L)

print("U:")
pprint.pprint(U)

print(m[0])


A:
array([[4, 1],
       [2, 3]])
P:
array([[1., 0.],
       [0., 1.]])
L:
array([[1. , 0. ],
       [0.5, 1. ]])
U:
array([[4. , 1. ],
       [0. , 2.5]])
2


Define the Numerical Alphabet relative dictionary.
Convert the Message into its numerical equivalent. 

In [2]:
import numpy as np
AlphaNums = { "a":1, "b":2, "c":3,"d":4, "e":5, "f":6, "g":7, "h":8, "i":9, "j":10, "k":11, "l":12, "m":13, "n":14, "o":15,"p":16, "q":17, "r":18, "s":19, "t":20, "u":21, "v":22, "w":23, "x":24, "y":25, "z":26, " ":0}
H=[]
file = open('DataSet1.txt', 'r')  
while 1: 
      
    # read by character 
    char = file.read(1)           
    if not char:  
        break

    H.append(char)
print(H)

Len = len(H)
print(Len)
file.close() 

#Converting message to a list
X = list()
N = list()
for ch in H:
    AlphaNums[ch.lower()]
    X.append(AlphaNums[ch.lower()])
print(X)
#Converting the numerical equivalent message into array blocks of size(2 x 1)
P = np.array(X)
print(P)
N=np.array_split(P,(Len/2))
print(N[0]) 

['T', 'h', 'e', ' ', 's', 't', 'u', 'd', 'y', ' ', 'o', 'f', ' ', 'm', 'e', 't', 'h', 'o', 'd', 's', ' ', 'f', 'o', 'r', ' ', 's', 'e', 'n', 'd', 'i', 'n', 'g', ' ', 'm', 'e', 's', 's', 'a', 'g', 'e', 's', ' ', 'i', 'n', ' ', 's', 'e', 'c', 'u', 'r', 'e', ' ', 'f', 'o', 'r', 'm', ' ', 'i', 'n', ' ', 's', 'u', 'c', 'h', ' ', 'a', ' ', 'w', 'a', 'y', ' ', 's', 'o', ' ', 't', 'h', 'a', 't', ' ', 'o', 'n', 'l', 'y', ' ', 'r', 'e', 'c', 'e', 'i', 'v', 'e', 'r', ' ', 'c', 'a', 'n', ' ', 'b', 'e', ' ', 'a', 'b', 'l', 'e', ' ', 't', 'o', ' ', 'r', 'e', 'a', 'd', ' ', 'i', 't', ' ', 'i', 's', ' ', 'k', 'n', 'o', 'w', 'n', ' ', 'a', 's', ' ', 'c', 'r', 'y', 'p', 't', 'o', 'g', 'r', 'a', 'p', 'h', 'y']
140
[20, 8, 5, 0, 19, 20, 21, 4, 25, 0, 15, 6, 0, 13, 5, 20, 8, 15, 4, 19, 0, 6, 15, 18, 0, 19, 5, 14, 4, 9, 14, 7, 0, 13, 5, 19, 19, 1, 7, 5, 19, 0, 9, 14, 0, 19, 5, 3, 21, 18, 5, 0, 6, 15, 18, 13, 0, 9, 14, 0, 19, 21, 3, 8, 0, 1, 0, 23, 1, 25, 0, 19, 15, 0, 20, 8, 1, 20, 0, 15, 14, 12, 25, 0, 18,

In [3]:
#Encrypt the message
#Apply Enccryption formula
K = np.dot(L,U)
print(K)
Ey=[]
J={}
C={}
k=int(Len/2);
for i in range(0,k):
    J[i] = (np.dot(K,N[i]))
    C[i]=J[i]%26
    C[i].tolist()
    Ey.extend(C[i])
print(Ey)

Encrypted=[]
for c in Ey:
    for K,V in AlphaNums.items():
        if V == (c):
            Encrypted.extend(K)
print(Encrypted)

Enystr="";
for a in Encrypted:
    Enystr += a
print("The Encrypted Message:")
print(Enystr)

[[4. 1.]
 [2. 3.]]
[10.0, 12.0, 20.0, 10.0, 18.0, 20.0, 10.0, 2.0, 22.0, 24.0, 14.0, 22.0, 13.0, 13.0, 14.0, 18.0, 21.0, 9.0, 9.0, 13.0, 6.0, 18.0, 0.0, 6.0, 19.0, 5.0, 8.0, 0.0, 25.0, 9.0, 11.0, 23.0, 13.0, 13.0, 13.0, 15.0, 25.0, 15.0, 7.0, 3.0, 24.0, 12.0, 24.0, 8.0, 19.0, 5.0, 23.0, 19.0, 24.0, 18.0, 20.0, 10.0, 13.0, 5.0, 7.0, 23.0, 9.0, 1.0, 4.0, 2.0, 19.0, 23.0, 20.0, 4.0, 1.0, 3.0, 23.0, 17.0, 3.0, 25.0, 19.0, 5.0, 8.0, 4.0, 10.0, 12.0, 24.0, 10.0, 15.0, 19.0, 16.0, 12.0, 22.0, 24.0, 25.0, 25.0, 17.0, 21.0, 6.0, 6.0, 12.0, 12.0, 3.0, 9.0, 18.0, 18.0, 2.0, 6.0, 20.0, 10.0, 6.0, 8.0, 1.0, 13.0, 20.0, 8.0, 8.0, 4.0, 25.0, 25.0, 8.0, 14.0, 9.0, 1.0, 2.0, 14.0, 3.0, 23.0, 11.0, 7.0, 19.0, 21.0, 2.0, 10.0, 1.0, 3.0, 24.0, 12.0, 4.0, 8.0, 12.0, 20.0, 17.0, 7.0, 20.0, 16.0, 20.0, 24.0, 5.0, 13.0]
['j', 'l', 't', 'j', 'r', 't', 'j', 'b', 'v', 'x', 'n', 'v', 'm', 'm', 'n', 'r', 'u', 'i', 'i', 'm', 'f', 'r', ' ', 'f', 's', 'e', 'h', ' ', 'y', 'i', 'k', 'w', 'm', 'm', 'm', 'o', 'y', 'o', '

In [4]:
#Decryption of a Message
#Find the inverse of LU
D = np.dot(L,U)
I = np.linalg.inv(D)
print(I)

[[ 0.3 -0.1]
 [-0.2  0.4]]


In [5]:
D1=[]
L={}
for j in range(0,k):
    L[j] = np.dot(I,J[j])%26
    print(L[j])
    D1.extend(L[j].tolist())
print(D1)

[20.  8.]
[5. 0.]
[19. 20.]
[21.  4.]
[25.  0.]
[15.  6.]
[26. 13.]
[ 5. 20.]
[ 8. 15.]
[ 4. 19.]
[26.  6.]
[15. 18.]
[ 0. 19.]
[ 5. 14.]
[4. 9.]
[14.  7.]
[26. 13.]
[ 5. 19.]
[19.  1.]
[7. 5.]
[19.  0.]
[ 9. 14.]
[ 0. 19.]
[5. 3.]
[21. 18.]
[5. 0.]
[ 6. 15.]
[18. 13.]
[26.  9.]
[14.  0.]
[19. 21.]
[3. 8.]
[26.  1.]
[26. 23.]
[ 1. 25.]
[ 0. 19.]
[15.  0.]
[20.  8.]
[ 1. 20.]
[ 0. 15.]
[14. 12.]
[25.  0.]
[18.  5.]
[3. 5.]
[ 9. 22.]
[ 5. 18.]
[26.  3.]
[ 1. 14.]
[26.  2.]
[5. 0.]
[1. 2.]
[12.  5.]
[ 0. 20.]
[15.  0.]
[18.  5.]
[1. 4.]
[26.  9.]
[20.  0.]
[ 9. 19.]
[26. 11.]
[14. 15.]
[23. 14.]
[26.  1.]
[19.  0.]
[ 3. 18.]
[25. 16.]
[20. 15.]
[ 7. 18.]
[ 1. 16.]
[ 8. 25.]
[20.0, 8.0, 5.0, 0.0, 18.999999999999996, 20.0, 21.0, 4.0, 25.0, 0.0, 15.0, 6.000000000000002, 26.0, 13.000000000000002, 5.0, 20.0, 7.999999999999999, 15.000000000000002, 4.0, 19.0, 26.0, 6.0, 14.999999999999998, 18.0, 0.0, 19.0, 4.999999999999999, 14.0, 4.0, 9.0, 13.999999999999998, 7.0, 26.0, 13.000000000000002, 4.99

In [6]:
D2=[]
for x in D1:
    for K,V in AlphaNums.items():
        if V == round(x):
            D2.extend(K)
print(D2)

Dcystr=""
for a in D2:
    Dcystr += a
print("The Decrypted Message:")
print(Dcystr)

['t', 'h', 'e', ' ', 's', 't', 'u', 'd', 'y', ' ', 'o', 'f', 'z', 'm', 'e', 't', 'h', 'o', 'd', 's', 'z', 'f', 'o', 'r', ' ', 's', 'e', 'n', 'd', 'i', 'n', 'g', 'z', 'm', 'e', 's', 's', 'a', 'g', 'e', 's', ' ', 'i', 'n', ' ', 's', 'e', 'c', 'u', 'r', 'e', ' ', 'f', 'o', 'r', 'm', 'z', 'i', 'n', ' ', 's', 'u', 'c', 'h', 'z', 'a', 'z', 'w', 'a', 'y', ' ', 's', 'o', ' ', 't', 'h', 'a', 't', ' ', 'o', 'n', 'l', 'y', ' ', 'r', 'e', 'c', 'e', 'i', 'v', 'e', 'r', 'z', 'c', 'a', 'n', 'z', 'b', 'e', ' ', 'a', 'b', 'l', 'e', ' ', 't', 'o', ' ', 'r', 'e', 'a', 'd', 'z', 'i', 't', ' ', 'i', 's', 'z', 'k', 'n', 'o', 'w', 'n', 'z', 'a', 's', ' ', 'c', 'r', 'y', 'p', 't', 'o', 'g', 'r', 'a', 'p', 'h', 'y']
The Decrypted Message:
the study ofzmethodszfor sendingzmessages in secure formzin suchzazway so that only receiverzcanzbe able to readzit iszknownzas cryptography
